"""Added Twitter Model

Revision ID: 62596c561945
Revises: 
Create Date: 2021-02-17 17:28:15.152117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62596c561945'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('screen_name', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('friends_count', sa.Integer(), nullable=True),
    sa.Column('listed_count', sa.Integer(), nullable=True),
    sa.Column('favourites_count', sa.Integer(), nullable=True),
    sa.Column('statuses_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('profile_image_url', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('oauth_token', sa.String(length=120), nullable=True),
    sa.Column('oauth_token_secret', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter')
    # ### end Alembic commands ###
