"""Added Tweet object to twitter_models and created one to many relationship of Twitter -> Tweet

Revision ID: 96858b4f6169
Revises: 62596c561945
Create Date: 2021-02-17 18:51:36.500490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96858b4f6169'
down_revision = '62596c561945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=80), nullable=True),
    sa.Column('text', sa.String(length=140), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=True),
    sa.Column('in_reply_to_status_id', sa.Integer(), nullable=True),
    sa.Column('in_reply_to_screen_name', sa.Integer(), nullable=True),
    sa.Column('in_reply_to_user_id', sa.Integer(), nullable=True),
    sa.Column('coordinates_latitude', sa.Integer(), nullable=True),
    sa.Column('coordinates_longitude', sa.Integer(), nullable=True),
    sa.Column('is_quote_status', sa.Boolean(), nullable=True),
    sa.Column('quote_status_id', sa.Integer(), nullable=True),
    sa.Column('retweeted_status_id', sa.Integer(), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('retweet_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('favorited', sa.Boolean(), nullable=True),
    sa.Column('retweeted', sa.Boolean(), nullable=True),
    sa.Column('possibly_sensitive', sa.Boolean(), nullable=True),
    sa.Column('filter_level', sa.String(length=80), nullable=True),
    sa.Column('lang', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['quote_status_id'], ['tweet.id'], ),
    sa.ForeignKeyConstraint(['retweeted_status_id'], ['tweet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['twitter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet')
    # ### end Alembic commands ###
