"""Added Album object to Spotify

Revision ID: c68c87d1db71
Revises: 6212138baae3
Create Date: 2021-02-24 13:00:42.147404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68c87d1db71'
down_revision = '6212138baae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_spotify_image_album_relationship_album_object'), 'album_object', ['album_relationship'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_spotify_image_spotify_relationship_spotify'), 'spotify', ['spotify_relationship'], ['id'])
        batch_op.drop_column('relationship')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('spotify_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_spotify_image_spotify_relationship_spotify'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_spotify_image_album_relationship_album_object'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'spotify', ['relationship'], ['id'])

    # ### end Alembic commands ###
