"""Added ListeningSession to track user music playing throughout the day

Revision ID: 1ee6e313628b
Revises: b50cdc5c575c
Create Date: 2021-03-15 11:01:07.433539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee6e313628b'
down_revision = 'b50cdc5c575c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listening_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp_begin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spotify_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spotify_id'], ['spotify.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_to_listening_session',
    sa.Column('track_id', sa.String(length=80), nullable=True),
    sa.Column('listening_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listening_session_id'], ['listening_session.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track_object.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_to_listening_session')
    op.drop_table('listening_session')
    # ### end Alembic commands ###
