"""Create relationship between spotify and topartists

Revision ID: 2ca79f627f8b
Revises: 2ff8bbc33862
Create Date: 2021-03-05 13:42:23.665990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca79f627f8b'
down_revision = '2ff8bbc33862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('topartist_to_spotify', 'spotify', ['spotify_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_artists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('spotify_id')

    # ### end Alembic commands ###
