"""Created Top Artists Object

Revision ID: 2ff8bbc33862
Revises: f516c6f16ef1
Create Date: 2021-03-05 13:29:08.497906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff8bbc33862'
down_revision = 'f516c6f16ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists_to_top_artists',
    sa.Column('artist_id', sa.String(length=80), nullable=True),
    sa.Column('top_artists_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist_object.id'], ),
    sa.ForeignKeyConstraint(['top_artists_id'], ['top_artists.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists_to_top_artists')
    op.drop_table('top_artists')
    # ### end Alembic commands ###
