"""Changed Artist ID and Album ID to strings

Revision ID: 603a70e42db4
Revises: 67e6a96935ca
Create Date: 2021-03-05 11:59:20.035344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603a70e42db4'
down_revision = '67e6a96935ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_relationship', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_artist_image', 'artist_object', ['artist_relationship'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artist_relationship')

    # ### end Alembic commands ###
