"""Added created_at field to user to track date of profile creation

Revision ID: 6212138baae3
Revises: f4655824c09a
Create Date: 2021-02-19 20:24:45.217307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6212138baae3'
down_revision = 'f4655824c09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
