"""Added ArtistObject

Revision ID: 67e6a96935ca
Revises: 8301a47de417
Create Date: 2021-03-03 12:17:01.110480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e6a96935ca'
down_revision = '8301a47de417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(length=120), nullable=True),
    sa.Column('href', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=6), nullable=True),
    sa.Column('uri', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album_to_artist',
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album_object.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artist_object.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_to_artist')
    op.drop_table('artist_object')
    # ### end Alembic commands ###
