"""Adding Album Object

Revision ID: 8301a47de417
Revises: 
Create Date: 2021-03-03 12:12:07.603082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8301a47de417'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('twitter_connected', sa.Boolean(), nullable=True),
    sa.Column('spotify_connected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.Column('friends', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('spotify',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('href', sa.String(length=80), nullable=True),
    sa.Column('product', sa.String(length=15), nullable=True),
    sa.Column('uri', sa.String(length=80), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('filter_enabled', sa.Boolean(), nullable=True),
    sa.Column('filter_locked', sa.Boolean(), nullable=True),
    sa.Column('external_urls', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=80), nullable=True),
    sa.Column('token_type', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=80), nullable=True),
    sa.Column('scopes', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('screen_name', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('friends_count', sa.Integer(), nullable=True),
    sa.Column('listed_count', sa.Integer(), nullable=True),
    sa.Column('favourites_count', sa.Integer(), nullable=True),
    sa.Column('statuses_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('profile_image_url', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('oauth_token', sa.String(length=120), nullable=True),
    sa.Column('oauth_token_secret', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spotify_image',
    sa.Column('url', sa.String(length=80), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('spotify_relationship', sa.Integer(), nullable=True),
    sa.Column('album_relationship', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_relationship'], ['album_object.id'], ),
    sa.ForeignKeyConstraint(['spotify_relationship'], ['spotify.id'], ),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=80), nullable=True),
    sa.Column('text', sa.String(length=140), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=True),
    sa.Column('in_reply_to_status_id', sa.Integer(), nullable=True),
    sa.Column('in_reply_to_screen_name', sa.Integer(), nullable=True),
    sa.Column('in_reply_to_user_id', sa.Integer(), nullable=True),
    sa.Column('coordinates_latitude', sa.Integer(), nullable=True),
    sa.Column('coordinates_longitude', sa.Integer(), nullable=True),
    sa.Column('is_quote_status', sa.Boolean(), nullable=True),
    sa.Column('quote_status_id', sa.Integer(), nullable=True),
    sa.Column('retweeted_status_id', sa.Integer(), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('retweet_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('favorited', sa.Boolean(), nullable=True),
    sa.Column('retweeted', sa.Boolean(), nullable=True),
    sa.Column('possibly_sensitive', sa.Boolean(), nullable=True),
    sa.Column('filter_level', sa.String(length=80), nullable=True),
    sa.Column('lang', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['quote_status_id'], ['tweet.id'], ),
    sa.ForeignKeyConstraint(['retweeted_status_id'], ['tweet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['twitter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet')
    op.drop_table('spotify_image')
    op.drop_table('twitter')
    op.drop_table('spotify')
    op.drop_table('followers')
    op.drop_table('user')
    # ### end Alembic commands ###
