"""Added AudioFeatures object

Revision ID: bc0deee8f644
Revises: 3e83a2d46e4b
Create Date: 2021-03-07 12:54:48.742476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0deee8f644'
down_revision = '3e83a2d46e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_features',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('uri', sa.String(length=120), nullable=True),
    sa.Column('track_href', sa.String(length=120), nullable=True),
    sa.Column('analysis_url', sa.String(length=120), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('time_signature', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track_object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_features')
    # ### end Alembic commands ###
