"""Added Top Tracks

Revision ID: c68f27259c7f
Revises: bc0deee8f644
Create Date: 2021-03-13 14:20:34.910306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68f27259c7f'
down_revision = 'bc0deee8f644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('spotify_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spotify_id'], ['spotify.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_to_top_tracks',
    sa.Column('track_id', sa.String(length=80), nullable=True),
    sa.Column('top_tracks_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['top_tracks_id'], ['top_tracks.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track_object.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_to_top_tracks')
    op.drop_table('top_tracks')
    # ### end Alembic commands ###
